name: "mdm_manage_engine_client"
description: "Dart client api for communicating with the MDM Manage Engine private appstore."
documentation: https://www.manageengine.com/mobile-device-management/api/
version: 0.1.0
publish_to: 'none' 

environment:
  sdk: ^3.5.3
dependencies:
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13



